"""Bundle edge_ai/ plus a slice of the comfort algorithm into one portable module tree.

    python edge-ai/deploy/build-edge-payload.py [--out <directory>]

`deploy-to-unoq.sh` calls this script and then transfers the result to the Arduino
UNO Q. Nobody runs it by hand, but it can be run to inspect what the slice contains.

WHY BUNDLE A SLICE RATHER THAN COPYING ALL OF src/:
  `comfort_bridge.py` deliberately imports the comfort algorithm DIRECTLY from the
  backend's `src/` rather than copying it — two copies would drift apart and give two
  different answers to "what temperature should this house be". That constraint is
  right, but it forces the deployment to carry a slice of the backend.

  Copying `src/` WHOLESALE breaks — tried on real hardware:

      File ".../src/app/models/__init__.py", line 7
        from app.models.app_release import AppRelease
      ModuleNotFoundError: No module named 'sqlalchemy'

  `comfort_bridge` only needs `app.models.enums.AcMode`, but Python runs the package's
  `__init__.py` BEFORE loading the submodule, and the real one imports all 12 ORM
  models. Installing SQLAlchemy on a field device to obtain one enum is the wrong
  direction, so `app/models/__init__.py` is replaced with an empty one.

THE RESULTING TREE — a single PYTHONPATH entry makes both importable:

    payload/
    ├── edge_ai/     the service
    └── app/         comfort + enums + schemas
"""

import argparse
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
EDGE_PKG = REPO / "edge-ai" / "edge_ai"
BACKEND = REPO / "src" / "app"

# The relative paths inside src/app/ that have to be carried. It follows the real
# import chain: comfort_engine -> comfort/*, models/enums, schemas/comfort (a pydantic
# model).
_BACKEND_FILES = [
    "__init__.py",
    "comfort/__init__.py",
    "comfort/comfort_constants.py",
    "comfort/comfort_engine.py",
    "comfort/ir_snap.py",
    "comfort/mode_decision.py",
    "comfort/room_aggregate.py",
    "comfort/running_mean.py",
    "comfort/setpoint_calculator.py",
    "models/enums.py",
    "schemas/__init__.py",
    "schemas/comfort.py",
]

_MODELS_INIT = '''"""DELIBERATELY EMPTY — not the backend's version.

The real src/app/models/__init__.py imports all 12 ORM models so Alembic can see them
on Base.metadata. Here only `app.models.enums.AcMode` is needed, and Python runs a
package's __init__.py before loading the submodule — so copying the real one across
would drag SQLAlchemy and the whole ORM onto a device that needs one enum.

Generated by edge-ai/deploy/build-edge-payload.py. Do not edit by hand.
"""
'''


def _copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def build(out: Path) -> int:
    # Wipe and rebuild: a file removed from the service but left behind in the payload
    # is still importable, and "I deleted it but the old error persists" is the kind of
    # failure that takes longest to track down.
    if out.exists():
        shutil.rmtree(out)

    n = 0
    for item in sorted(EDGE_PKG.glob("*.py")):
        _copy(item, out / "edge_ai" / item.name)
        n += 1
    for rel in _BACKEND_FILES:
        src = BACKEND / rel
        if not src.is_file():
            print(f"THIEU {src} — lat cat khong con khop voi backend.", file=sys.stderr)
            return 1
        _copy(src, out / "app" / rel)
        n += 1

    (out / "app" / "models" / "__init__.py").write_text(_MODELS_INIT, encoding="utf-8")
    print(f"{out}: {n + 1} file")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent / "payload",
                    help="thu muc ket qua (mac dinh: edge-ai/deploy/payload)")
    raise SystemExit(build(ap.parse_args().out))
