#pragma once
#include <Arduino.h>   // isnan() and the basic types -- lvgl.h does not pull in math.h
#include <lvgl.h>

// Vietnamese fonts generated with lv_font_conv, see the Font section below.
// They MUST be declared at global scope, outside every namespace.
LV_FONT_DECLARE(aircon_viet_12);
LV_FONT_DECLARE(aircon_viet_16);
LV_FONT_DECLARE(aircon_num_28);
LV_FONT_DECLARE(aircon_num_40);

// Embedded images, generated by tools/make_lvgl_images.py from
// Interface/LVGL/assets/.
// Also at global scope, for the same reason as the fonts: inside a namespace C++
// mangles the variable name while the .c file defines it at global scope -- and the
// error only surfaces at LINK time, not at compile time.
LV_IMG_DECLARE(img_bg_tech);   // 320x240 dark technical background
LV_IMG_DECLARE(img_ac_unit);   // 44x26  indoor unit
LV_IMG_DECLARE(img_plus);      // 22x22  plus sign
LV_IMG_DECLARE(img_minus);     // 22x22  minus sign

// ============================================================================
//  The "Titanium Command" design system for a 320x240 screen.
// ----------------------------------------------------------------------------
//  TAKEN FROM TWO SOURCES, DELIBERATELY -- read this before changing any colour:
//
//    GEOMETRY <- src/app/web/static/ds/tokens/foundation/shapes.css
//                + ds/platforms/kiosk.css  (45° chamfers, no rounding, thick borders)
//    COLOUR   <- app-flutter/lib/theme/ac_colors.dart  (the DARK CARBON palette)
//
//  That sounds contradictory but is not: geometry is what identifies the brand and
//  is THE SAME everywhere; colour follows THE CONTEXT OF USE. A wall panel serves
//  the customer inside the room -- the same audience and the same environment as
//  the phone app (dark background). The admin web's light #f0f2f5 background is a
//  staff screen, viewed on a laptop in daylight. Carrying that light background
//  onto the panel would glare in your face at night.
//
//  The anchor holding the two systems together is THE ACCENT COLOUR #0055FF --
//  identical on both web and app. Changing the accent breaks that link.
//
//  THE DESIGN SYSTEM'S THREE SIGNATURES, which must not be got wrong:
//
//  1. NO ROUNDED CORNERS. shapes.css says outright "NO ROUNDED CORNERS" -- only 45°
//     chamfers, and only on TWO corners: TOP-LEFT + BOTTOM-RIGHT. Chamfering all
//     four is a completely different symbol, not a minor aesthetic variation.
//  2. UPPERCASE, LETTER-SPACED LABELS. This is what makes the UI read as
//     "engineering".
//  3. BORDERS THICKER than ordinary web (kiosk.css: --border-width-md 2px) for
//     legibility at standing distance.
//
//  Chamfer sizes are scaled to the screen: the web uses 8/12/20 px on a 1920-wide
//  frame. Kept unchanged at 320 px the chamfer would consume an entire button --
//  reduced to 4/6/10.
// ============================================================================
namespace Theme {

// --- Colour: the DARK palette, from app-flutter/lib/theme/ac_colors.dart ------
//  WHY IT FOLLOWS THE APP AND NOT THE ADMIN WEB (which is light, #f0f2f5):
//  the person standing at the wall panel is the CUSTOMER -- they also use the phone
//  app, which is already dark. The admin web is the SALES STAFF's screen, viewed on
//  a laptop. A white-background panel would also glare at night in a bedroom.
//
//  The key point: THE ACCENT COLOUR #0055FF IS IDENTICAL in both systems. Only the
//  neutrals flip; the brand signature does not change -- so the panel still reads as
//  "the same product" as the web.
//  THIS IS THE SINGLE SOURCE OF TRUTH FOR COLOUR. This table matches the swatch
//  strip at the bottom of Interface/mockup.svg exactly -- change it here and rerun
//  tools/make_mockup.py, do not let the two say different things.
//
//  The screen background (#0C193B, navy) and the card background (#141C28, stone
//  grey) are nearly equal in brightness but DIFFERENT IN HUE -- a card separates
//  from the background by hue plus the bright #3E5468 border, not by a
//  light/dark contrast. This is deliberate: strong light/dark contrast on a
//  wall-mounted panel at night turns into glaring rectangles.
inline lv_color_t bgPrimary()     { return lv_color_hex(0x0C193B); } // screen background
inline lv_color_t bgSecondary()   { return lv_color_hex(0x141C28); } // card background
inline lv_color_t bgElevated()    { return lv_color_hex(0x1E2B3C); } // button background -- raised above the card
inline lv_color_t bgSubtle()      { return lv_color_hex(0x101722); } // a disabled button, sunk below
inline lv_color_t textPrimary()   { return lv_color_hex(0xE7F1F8); }
inline lv_color_t textMuted()     { return lv_color_hex(0x8DA2B5); }
inline lv_color_t textCode()      { return lv_color_hex(0x8DA2B5); }
inline lv_color_t borderSubtle()  { return lv_color_hex(0x2A3B4C); } // carbonLine
inline lv_color_t borderDefault() { return lv_color_hex(0x3E5468); } // carbonLineBright
inline lv_color_t borderStrong()  { return lv_color_hex(0xE7F1F8); }
inline lv_color_t accent()        { return lv_color_hex(0x0055FF); } // ice -- SAME as the web
inline lv_color_t accentDown()    { return lv_color_hex(0x0044CC); }
inline lv_color_t accentText()    { return lv_color_hex(0x4D8DFF); } // iceText -- accented numbers on dark
inline lv_color_t ok()            { return lv_color_hex(0x22C55E); }
inline lv_color_t err()           { return lv_color_hex(0xFF4D4D); }
inline lv_color_t warn()          { return lv_color_hex(0xF5A623); }

/// BLACK or WHITE text on background [bg] -- chosen by perceived luminance, not
/// guessed.
///
/// Needed because badges and primary buttons use many different backgrounds: white
/// on #0055FF blue is clear, but white on #F5A623 amber is barely legible.
/// Hard-coding one text colour is guaranteed to be wrong half the time.
lv_color_t onColor(lv_color_t bg);

/// Colour from the THERMAL SCALE -- it expresses MEANING (cold / comfortable / warm
/// / hot) and never the SOURCE ("an indoor or outdoor sensor"). The same rule as
/// --ac-cold / --ac-neutral / --ac-warm / --ac-hot in app.css.
lv_color_t thermal(float tempC);

// --- Grid: A CONTRACT with ../../Interface/README.md §5 -----------------------
//  Change a number here and you must change the wireframe over there, otherwise the
//  next person to read the documentation gets it wrong.
enum : lv_coord_t {
  SCREEN_W  = 320, SCREEN_H = 240,
  PAD       = 6,
  STATUS_H  = 22,          // y 0..21
  CONTENT_Y = 24, CONTENT_H = 180,   // y 24..203
  // NAV_W IS GONE. The tab count has changed twice (4 -> 5 -> 6) and each time a
  // width dividing 320 evenly had to be found: 80, then 64, then... 53.33. There is
  // no integer for 6 tabs, so committing to a constant means accepting either 2
  // surplus pixels on the right (the accent bar under the last tab not reaching the
  // edge, which looks like a drawing bug) or overflowing off the screen.
  //
  // Widths are now computed from BOUNDARIES rather than from a width: tab i runs
  // from (320*i)/TABS to (320*(i+1))/TABS. The remainder is spread evenly -- 6 tabs
  // give 53,54,53,53,54,53 = exactly 320 -- and adding a tab later requires no
  // recalculation at all. See tabX()/tabW() in ui-screens.cpp.
  NAV_Y     = 206, NAV_H = 34,
  CH_SM = 4, CH_MD = 6, CH_LG = 10           // chamfer sizes
};

/// Chamfer the TOP-LEFT + BOTTOM-RIGHT corners of an LVGL object.
///
/// LVGL has no chamfer style -- `radius` only rounds. So it is drawn by hand at
/// LV_EVENT_DRAW_POST_END: two triangles filled with the colour behind to "cut" the
/// corners away, then two diagonal border-coloured lines so the border stays
/// continuous. Far cheaper than building a mask, and it preserves the geometric
/// signature.
///
/// [bgBehind] is the colour IMMEDIATELY BEHIND the object (the screen background,
/// or the card background if the object is inside a card). Get it wrong and the
/// corners show streaks.
void chamfer(lv_obj_t *obj, lv_coord_t size, lv_color_t bgBehind);

// --- Fonts: ACCENTED VIETNAMESE ----------------------------------------------
//  Generated by tools/make_lvgl_fonts.ps1 (lv_font_conv) from Arial, emitted to
//  fonts/aircon_*.c. Do NOT use LVGL's built-in Montserrat: it only has ASCII + °
//  + •, so "LÀM LẠNH" comes out as boxes or with the diacritics dropped.
//
//  Two font groups with different purposes:
//   - viet_12 / viet_16 : full 0x1EA0-0x1EF9 (every Vietnamese diacritic), 2 bpp.
//     2 bpp rather than 4 halves the size -- on a 2.8" screen at standing distance
//     the eye cannot tell, and it saves ~70 KB of flash.
//   - num_28 / num_40   : ONLY digits + ° C % + - . -- temperatures and setpoints
//     never contain Vietnamese letters, and embedding the whole diacritic table at
//     40 px would waste ~90 KB. 4 bpp because large numbers sit at eye level where
//     aliasing is obvious.
//  The declarations live OUTSIDE namespace Theme (at the top of this file) -- inside
//  a namespace the compiler mangles them to `Theme::aircon_num_40` while the font
//  file defines them at global scope, and the error only surfaces at LINK time
//  rather than at compile time.

const lv_font_t *fontHero();   // 40, digits only -- large temperature / setpoint
const lv_font_t *fontBig();    // 28, digits only -- medium numbers
const lv_font_t *fontTitle();  // 16 bold, accented -- card headings
const lv_font_t *fontBody();   // 16 bold, accented -- body text
const lv_font_t *fontLabel();  // 12, accented -- labels
const lv_font_t *fontTiny();   // 12, accented -- captions

// --- Construction helpers ----------------------------------------------------
/// Call once from Ui::begin(), after lv_init().
void init();

/// A card: pale background, thin border, corners already chamfered.
lv_obj_t *card(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h);

/// A button. [primary] = accent-blue background (the primary action); otherwise a
/// pale outlined background.
lv_obj_t *button(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h,
                 const char *text, bool primary = false);

/// A button carrying an IMAGE rather than text (temperature up / down).
///
/// Images rather than the font's "+" and "-" characters, because the ASCII minus
/// (0x2D) is a HYPHEN -- it is stubby and sits off the centre line, so next to a
/// full-size "+" the pair looks misaligned. The true mathematical minus (U+2212) is
/// not in the numeric font's character set. Images solve both, and they match the
/// icon set the designer already drew.
lv_obj_t *buttonImg(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w, lv_coord_t h,
                    const lv_img_dsc_t *src);

/// Attach the press sound. ui.cpp passes BoardIo::beep in here.
///
/// Through a function pointer rather than #include "board-io.h": the theme is the
/// DRAWING layer and must not know whether the board has a buzzer. The other way
/// round, every hardware change would mean editing the UI design file.
void setPressSound(void (*fn)());

/// Give a HAND-BUILT button (one not created via button()) full feedback: colour
/// change + sound. Used for the tab buttons, which are built directly with
/// lv_btn_create.
void pressFeedback(lv_obj_t *btn);

/// The currently selected button (the running mode) -- filled with the accent
/// colour.
void buttonSelect(lv_obj_t *btn, bool selected);

/// Dimmed and unpressable (no IR code learned). Do NOT hide the button: the user
/// has to see that it exists and understand why it is unusable -- "no dead keys"
/// (README §4.1).
void buttonDisable(lv_obj_t *btn, bool disabled);

/// An ordinary label. [font]=nullptr uses fontBody().
lv_obj_t *label(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, const char *text,
                const lv_font_t *font = nullptr, lv_color_t color = textPrimary());

/// An UPPERCASE letter-spaced label in --text-muted -- the design system's label
/// style.
lv_obj_t *labelCaps(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, const char *text);

// --- Motion tokens (design-guiline/src/styles/animations/motion-tokens.css) ---
//  The numbers are copied verbatim from the design system so the panel and the web
//  move at the same rhythm. LVGL has no arbitrary cubic-bezier;
//  lv_anim_path_ease_out is the closest approximation to --ease-out.
enum : uint32_t {
  DUR_INSTANT = 100,   // touch feedback
  DUR_FAST    = 150,   // colour change, on/off
  DUR_NORMAL  = 250,   // card selection, state change
  DUR_SLOW    = 400,   // page transition
  DUR_SHIMMER = 1500   // one sweep of the skeleton
};

/// A SKELETON bar: a placeholder for data that HAS NOT ARRIVED, with a bright band
/// sweeping across it.
///
/// Why not just "--": a dash looks like a VALUE, and a wrong one. Someone standing
/// at the panel cannot tell "not measured yet" from "the sensor is broken". A
/// moving highlight says WAITING outright -- with no words at all.
///
/// The web version (effects.css) uses a 3-stop gradient animated through
/// background-position. LVGL 8.3 only has 2-stop gradients, so here it is a bright
/// rectangle sliding inside a background rectangle -- the same effect, and cheaper
/// because only the bright rectangle's region is redrawn.
lv_obj_t *skeleton(lv_obj_t *parent, lv_coord_t x, lv_coord_t y,
                   lv_coord_t w, lv_coord_t h, uint32_t delayMs = 0);

/// Show/hide a skeleton. Hiding also stops the animation -- leaving it running would
/// pointlessly redraw a region nobody can see, every 20 ms, forever.
void skeletonShow(lv_obj_t *sk, bool show);

/// Make [page]'s children SLIDE IN from both sides and settle into place.
/// Even-indexed children enter from the left, odd-indexed from the right.
///
/// [dist] is DELIBERATELY SHORT (28 px, not a whole screen) and [ms] deliberately
/// fast. This is a hardware constraint, not a matter of taste: 27 MHz SPI takes
/// ~46 ms to push a full 320x240 frame (76,800 pixels x 16 bits / 27 MHz), so a
/// full-page slide only manages a few frames and comes out juddering -- i.e. an
/// effect added for smoothness ends up less smooth than none at all. A short slide
/// keeps the redrawn region small, the frames keep up, and the eye reads it as
/// "snapping into place".
///
/// Each child's destination is stored in user_data on the first call, so rapidly
/// switching tabs while an animation is still running does not make them drift.
void slideIn(lv_obj_t *page, lv_coord_t dist = 28, uint32_t ms = DUR_FAST);

/// A small badge (AUTO / OVERRIDE). [bg] is the background, the text is white.
lv_obj_t *badge(lv_obj_t *parent, lv_coord_t x, lv_coord_t y, lv_coord_t w,
                const char *text, lv_color_t bg);

} // namespace Theme
