#pragma once
#include <Arduino.h>

// ============================================================================
//  Infrared code store in NVS (flash), keyed by the backend's ir_code_id.
// ----------------------------------------------------------------------------
//  WHY IT IS NEEDED: the backend only includes `ir_raw` on the FIRST use of each
//  ir_code_id; after that it trusts that the node has kept the code in flash and
//  sends only the id (command_publisher._resolve_ir_raw + redis_ir_cache). Without
//  this store, from the second command onwards the node holds an id and has no
//  idea what to transmit.
//
//  Codes survive power loss and even a firmware reflash (NVS lives in its own
//  partition, which `pio run -t upload` does not touch) -- but `erase_flash` wipes
//  them; see ../README.md §6, the "cache mismatch" entry.
// ============================================================================
namespace IrStore {

/// Open the NVS namespace. Returns false if the NVS partition is corrupt/full.
bool begin();

/// Store (or overwrite) the timing array for one ir_code_id.
bool save(const char *irCodeId, const uint16_t *raw, uint16_t len);

/// Read into [out]. Returns how many marks were read; 0 means NOT PRESENT (never
/// stored, or longer than maxLen). It never returns a truncated array -- an IR
/// frame missing its tail is a completely different command, and transmitting it
/// is worse than transmitting nothing.
uint16_t load(const char *irCodeId, uint16_t *out, uint16_t maxLen);

/// Wipe the whole store (used to force the backend to resend every ir_raw).
void wipe();

/// How many codes are currently held (tracked by a separate counter, see the .cpp)
/// -- for the THONG TIN screen.
uint16_t count();

// ---------------------------------------------------------------------------
//  ALIAS index (mode, temp) -> ir_code_id
// ---------------------------------------------------------------------------
//  WHY IT IS NEEDED: the store above is keyed by ir_code_id -- a UUID generated by
//  the backend. The node has no reverse lookup, so when the user presses "COOL 26"
//  ON THE NODE'S OWN SCREEN it does not know which frame to transmit.
//
//  The cheapest fix: every time the backend sends a command it already includes
//  `mode` + `setpoint` + `ir_code_id`. Storing an extra key "aCOOL26" -> id lets
//  the node build its own reverse lookup with no backend change at all.
//
//  TWO SOURCES FILL THIS TABLE, and both are required:
//    1. The backend sends a command with `ir_raw` -> save() + saveAlias() with the
//       real UUID.
//    2. The node learns a code itself -> saveLearned() with a temporary id (see
//       below).
//  With only source 1, the panel cannot use the very code it has just taught and
//  has to wait for the server to happen to send a command for that combination --
//  which looks exactly like a fault.
//
//  Any combination with no code from either source leaves its button dimmed, and
//  the control screen is required to state the reason -- no dead keys.
//
//  [temp] < 0 means a fixed code with no temperature (DRY/FAN/OFF).
// ---------------------------------------------------------------------------
bool saveAlias(const char *mode, int temp, const char *irCodeId);

/// Store a code JUST LEARNED at the node, under a temporary id the node generates
/// itself.
///
/// WHY IT IS NEEDED: right after learning, the node has only UPLOADED the timing
/// array to the cloud -- `ir_code_id` is a UUID generated by the backend, so the
/// node does not know it yet. Relying only on the `save()` path above (which runs
/// when the backend sends a command with `ir_raw`) leaves a very awkward gap: **the
/// user has just taught a code on the panel, and that same panel still reports
/// "CHƯA HỌC MÃ" with every mode button dimmed** -- until the server's comfort loop
/// happens to send down a command for that exact combination. On a wall-mounted
/// control panel that reads as broken, not as "waiting".
///
/// The temporary id carries its own prefix to distinguish it from a real UUID.
/// When the backend does send a real command for the same combination,
/// `saveAlias()` repoints the alias at that UUID and ALSO CLEANS UP the temporary
/// array -- otherwise each code occupies two slots and the 20 KB NVS partition is
/// not enough for the 18 required combinations (COOL 16..30 + DRY + FAN + OFF).
///
/// [temp] < 0 for fixed codes (DRY/FAN/OFF), the same convention as saveAlias().
bool saveLearned(const char *mode, int temp, const uint16_t *raw, uint16_t len);

/// true if a code exists for this combination (used to dim unlearned buttons).
bool hasAlias(const char *mode, int temp);

/// Delete a combination's code: removes both the alias and the timing array it
/// points at.
///
/// ONLY DELETES ON THE NODE. The `ir_codes` row in Postgres remains, so this is
/// "forget it so it can be reloaded" rather than "delete permanently" -- to delete
/// it for good, use the app (DELETE /api/v1/ir/codes/{id}).
///
/// A CONSEQUENCE YOU MUST KNOW: the backend remembers "this node has this code" in
/// Redis (`bl:ircache:{id}`) and from the second command onwards sends only the
/// bare `ir_code_id`. Delete without doing anything more and the next command for
/// this combination lands in main.cpp's "have an id but NVS is empty" branch and
/// the air conditioner sits still. That is why that branch publishes `need_raw` so
/// the backend clears its cache and resends the array -- these two halves have to
/// travel together, and dropping one creates a silent failure.
///
/// Returns false if the combination had no code in the first place (not treated as
/// an error, there was simply nothing to delete).
bool removeAlias(const char *mode, int temp);

/// Look up the alias and read the timing array in one go. Returns 0 if absent.
uint16_t loadAlias(const char *mode, int temp, uint16_t *out, uint16_t maxLen);

} // namespace IrStore
